### ISSUE TITLE
Error "Invalid address specified to RtlValidateHeap" in release mode

### ISSUE THREAD

**Issue by luisparedes04** [cutelyst/simple-mail#25] opened 2019-10-24 19:34 UTC
Hi, 
I have been using this library for a small application and in debug mode everything works just fine but when I try to run the program in release mode the application still sends the email but, right after is sent, the application crashes.
this is the error I get:
__cdecl SimpleMail::MimePart::~MimePart(void)
__cdecl SimpleMail::MimePart::~MimePart(void)
HEAP[Viewer.exe]: Invalid address specified to RtlValidateHeap( 00000169E72D0000, 0000169F571FA00 )

Could anyone help me with this?

**Comment by dantti** [comment] 2019-10-25 13:07
do you have a better backtrace?

**Comment by dantti** [comment] 2019-11-10 16:06
closing as I cannot reproduce, please try if possible with the new async API

**Closed by dantti** 2019-11-10 16:06 UTC
